## 카이제곱 검정 개요

- 목적 : 두 범주형 변수가 서로 독립적인 검증
    
        - 귀무가설 : 두 변수가 서로 독립
        - 대립가설 : 두 변수가 서로 종속
- 교차 테이블(분할표)로 시각화

## 교차 테이블 (분할표)
- 두 변수가 취할 수 있는 값 조합의 출현 빈도를 나타냄 

![](../picture/분할표.png)

![](../picture/분할표위치.PNG)

![](../picture/관측값.png)

![](../picture/n11기대값.png)

![](../picture/카이기대값1.png)

![](../picture/카이제곱함수.png)

![](../picture/카이제곱통계량계산.PNG)

![](../picture/카이제곱함수.PNG)

- 기대값과 실제값의 차이가 클수록 통계량이 커지게 됨
- 통계량이 커질수록 p-value가 감소함
- 귀무가설이 기각될 가능성이 높아짐

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import* 

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"


In [5]:
df = pd.read_csv("../data/htest05.csv", engine = "python") #폐암과 흡연의 연관성 분석
df.head()
df.tail()


smoke  disease
0      0        0
1      0        0
2      0        0
3      0        0
4      0        0

smoke  disease
30      1        0
31      1        1
32      1        1
33      1        1
34      1        1

## 분할표 작성
- pd.crosstab()
- 범주형 변수로 되어있는 요인(factors)별로 교차분석(cross tabulations) 해서, 행, 열 요인 기준 별로 빈도를 세어서 도수분포표(frequency table), 교차표(contingency table) 를 만들어줌


![](../picture/데이터재구조화.png)

In [7]:
# 교차 테이블 생성 (분할표)
cross_t = pd.crosstab(df['smoke'], df['disease'])
cross_t
type(cross_t)

disease   0  1
smoke         
0        14  2
1        10  9

pandas.core.frame.DataFrame

In [8]:
obs = cross_t.values
obs

array([[14,  2],
       [10,  9]], dtype=int64)

In [9]:
statistics, pvalue, dof, expected = chi2_contingency(obs, correction=False)
# 통계량, pvalue, 자유도, 기대값


pvalue # 귀무가설이 기각 - 흡연과 폐암 유무는 연관성이 있음

0.026855610352114926

In [27]:
# 기대값
pd.DataFrame(expected, columns=cross_t.columns, index=cross_t.index)

disease          0         1
smoke                       
0        10.971429  5.028571
1        13.028571  5.971429

## 성별에 따라 만족도가 달라지는 - 성별과 만족도는 독립적인지 검정

In [10]:
# 교차 테이블
df = pd.read_csv("../data/성별에따른만족도.csv", engine = "python", encoding='euc-kr')
df.head()


만족도  성별
0  불만족  남성
1   보통  여성
2  불만족  여성
3   보통  남성
4   만족  여성

In [11]:
cross_t = pd.crosstab( df['만족도'],df['성별'])

In [12]:
obs = cross_t.values
## array 형태로 변경
obs

array([[50, 40],
       [40, 30],
       [10, 30]], dtype=int64)

In [13]:
chi2_contingency(obs, correction=False)

(12.53968253968254,
 0.001892528960792166,
 2,
 array([[45., 45.],
        [35., 35.],
        [20., 20.]]))